/** Domain types shared by services, UI, and API adapters — no Node/SQLite coupling. */
export type {
  Product,
  ProductInput,
  AdminProductFilters,
  Order,
  OrderItem,
  OrderStatus,
  OrderFilters,
  OrderRow,
  User,
  DashboardStats,
  ClientRow as CustomerRow,
  OrderInput,
  Category,
  Brand,
  CustomerDetail,
  Conversation,
  AdminUser,
} from './domain';
